const cfg=window.FS_SUPABASE;
const db=window.supabase.createClient(cfg.url,cfg.publishableKey);
const authView=document.querySelector("#auth-view"),adminView=document.querySelector("#admin-view"),authMessage=document.querySelector("#auth-message"),formMessage=document.querySelector("#form-message"),creationForm=document.querySelector("#creation-form");
let creations=[];document.querySelector("#email").value=cfg.adminEmail;
function message(el,text,type=""){el.textContent=text;el.className=`message ${type}`}
function busy(button,on,label){if(!button.dataset.label)button.dataset.label=button.textContent;button.disabled=on;button.textContent=on?label:button.dataset.label}
function authorized(user){return user?.email?.toLowerCase()===cfg.adminEmail.toLowerCase()}
async function showSession(session){if(session&&!authorized(session.user)){await db.auth.signOut();session=null}authView.hidden=!!session;adminView.hidden=!session;if(session){document.querySelector("#signed-user").textContent=session.user.email;await loadCreations()}}
document.querySelector("#login-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.submitter;busy(button,true,"Entrando…");message(authMessage,"");const {data,error}=await db.auth.signInWithPassword({email:cfg.adminEmail,password:document.querySelector("#password").value});busy(button,false);if(error)return message(authMessage,"Não foi possível entrar. Confira a senha ou use ‘Primeiro acesso’.","error");await showSession(data.session)});
document.querySelector("#signup-button").addEventListener("click",async e=>{const password=document.querySelector("#password").value;if(password.length<8)return message(authMessage,"Crie uma senha com pelo menos 8 caracteres.","error");busy(e.currentTarget,true,"Criando…");const redirect=`${location.origin}${location.pathname}`;const {data,error}=await db.auth.signUp({email:cfg.adminEmail,password,options:{emailRedirectTo:redirect}});busy(e.currentTarget,false);if(error)return message(authMessage,"Não foi possível criar o acesso: "+error.message,"error");if(data.session)return showSession(data.session);message(authMessage,"Pronto! Abra o e-mail da FS Studio Maker e confirme o acesso. Depois volte aqui e clique em Entrar.","success")});
document.querySelector("#logout").addEventListener("click",async()=>{await db.auth.signOut();location.reload()});document.querySelector("#refresh").addEventListener("click",loadCreations);
function publicUrl(path){return db.storage.from("creations").getPublicUrl(path).data.publicUrl}function escapeHtml(value){const el=document.createElement("span");el.textContent=value||"";return el.innerHTML}
async function loadCreations(){const list=document.querySelector("#creation-list");list.innerHTML="<p>Carregando…</p>";const {data,error}=await db.from("creations").select("*,creation_images(*)").order("sort_order").order("created_at",{ascending:false});if(error){list.innerHTML=`<p>Erro ao carregar: ${escapeHtml(error.message)}</p>`;return}creations=data||[];if(!creations.length){list.innerHTML="<p>Nenhuma criação cadastrada ainda.</p>";return}list.innerHTML=creations.map(item=>{const imgs=(item.creation_images||[]).sort((a,b)=>a.sort_order-b.sort_order);return `<article class="list-item"><img src="${imgs[0]?publicUrl(imgs[0].storage_path):"assets/colecionaveis.jpg"}" alt=""><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.category||"Sem categoria")}${item.show_price&&item.price!=null?` · € ${Number(item.price).toFixed(2)}`:""}</p><span class="status ${item.published?"":"draft"}">${item.published?"Publicado":"Rascunho"}</span></div><div class="item-actions"><button data-edit="${item.id}">Editar</button><button class="delete" data-delete="${item.id}">Excluir</button></div></article>`}).join("");list.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editCreation(b.dataset.edit)));list.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>deleteCreation(b.dataset.delete)))}
function resetForm(){creationForm.reset();document.querySelector("#creation-id").value="";document.querySelector("#published").checked=true;document.querySelector("#sort-order").value=0;document.querySelector("#form-title").textContent="Nova criação";document.querySelector("#cancel-edit").hidden=true;document.querySelector("#existing-images").innerHTML="";message(formMessage,"")}
function editCreation(id){const item=creations.find(x=>x.id===id);if(!item)return;document.querySelector("#creation-id").value=item.id;document.querySelector("#title").value=item.title;document.querySelector("#description").value=item.description||"";document.querySelector("#category").value=item.category||"";document.querySelector("#price").value=item.price??"";document.querySelector("#show-price").checked=item.show_price;document.querySelector("#published").checked=item.published;document.querySelector("#featured").checked=item.featured;document.querySelector("#sort-order").value=item.sort_order||0;document.querySelector("#form-title").textContent="Editar criação";document.querySelector("#cancel-edit").hidden=false;renderExisting(item);creationForm.scrollIntoView({behavior:"smooth"})}
function renderExisting(item){const box=document.querySelector("#existing-images");box.innerHTML=(item.creation_images||[]).sort((a,b)=>a.sort_order-b.sort_order).map(img=>`<div class="existing-image"><img src="${publicUrl(img.storage_path)}" alt=""><button type="button" data-remove-image="${img.id}" aria-label="Remover foto">×</button></div>`).join("");box.querySelectorAll("[data-remove-image]").forEach(btn=>btn.addEventListener("click",()=>removeImage(btn.dataset.removeImage,item.id)))}
async function removeImage(imageId,creationId){const item=creations.find(x=>x.id===creationId),img=item?.creation_images?.find(x=>x.id===imageId);if(!img||!confirm("Remover esta foto?"))return;const storageResult=await db.storage.from("creations").remove([img.storage_path]);if(storageResult.error)return message(formMessage,"Erro ao remover a foto: "+storageResult.error.message,"error");const {error}=await db.from("creation_images").delete().eq("id",imageId);if(error)return message(formMessage,"Erro ao remover o registro da foto: "+error.message,"error");await loadCreations();editCreation(creationId)}
creationForm.addEventListener("submit",async e=>{e.preventDefault();const button=document.querySelector("#save-button"),id=document.querySelector("#creation-id").value;busy(button,true,"Salvando…");message(formMessage,"");const rawPrice=document.querySelector("#price").value,payload={title:document.querySelector("#title").value.trim(),description:document.querySelector("#description").value.trim()||null,category:document.querySelector("#category").value.trim()||null,price:rawPrice===""?null:Number(rawPrice),show_price:document.querySelector("#show-price").checked,published:document.querySelector("#published").checked,featured:document.querySelector("#featured").checked,sort_order:Number(document.querySelector("#sort-order").value)||0,updated_at:new Date().toISOString()};let creationId=id;if(id){const {error}=await db.from("creations").update(payload).eq("id",id);if(error){busy(button,false);return message(formMessage,"Erro ao salvar: "+error.message,"error")}}else{const {data,error}=await db.from("creations").insert(payload).select("id").single();if(error){busy(button,false);return message(formMessage,"Erro ao cadastrar: "+error.message,"error")}creationId=data.id}const files=[...document.querySelector("#images").files];for(let index=0;index<files.length;index++){const file=files[index];if(file.size>8*1024*1024){busy(button,false);return message(formMessage,`A foto ${file.name} ultrapassa 8 MB.`,"error")}const ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=`${creationId}/${crypto.randomUUID()}.${ext}`;const upload=await db.storage.from("creations").upload(path,file,{cacheControl:"3600",upsert:false});if(upload.error){busy(button,false);return message(formMessage,"Criação salva, mas uma foto falhou: "+upload.error.message,"error")}const imageRow=await db.from("creation_images").insert({creation_id:creationId,storage_path:path,alt_text:payload.title,sort_order:index});if(imageRow.error){await db.storage.from("creations").remove([path]);busy(button,false);return message(formMessage,"Erro ao registrar uma foto: "+imageRow.error.message,"error")}}busy(button,false);resetForm();await loadCreations();message(formMessage,"Criação salva com sucesso!","success")});
async function deleteCreation(id){const item=creations.find(x=>x.id===id);if(!item||!confirm(`Excluir “${item.title}” e todas as fotos?`))return;const paths=(item.creation_images||[]).map(x=>x.storage_path);if(paths.length){const removed=await db.storage.from("creations").remove(paths);if(removed.error)return alert("Não foi possível remover as fotos: "+removed.error.message)}const {error}=await db.from("creations").delete().eq("id",id);if(error)return alert("Não foi possível excluir: "+error.message);if(document.querySelector("#creation-id").value===id)resetForm();await loadCreations()}
document.querySelector("#cancel-edit").addEventListener("click",resetForm);db.auth.onAuthStateChange((_event,session)=>setTimeout(()=>showSession(session),0));db.auth.getSession().then(({data})=>showSession(data.session));
