const cfg=window.FS_SUPABASE;
const db=window.supabase.createClient(cfg.url,cfg.publishableKey);
const copy={it:{back:"← Torna al sito",kicker:"Le nostre creazioni",title:"Idee diventate realtà.",intro:"Scopri alcuni progetti realizzati e contattaci per crearne uno tutto tuo.",all:"Tutte",loading:"Caricamento delle creazioni…",empty:"Il catalogo sarà aggiornato presto. Scrivici per raccontarci la tua idea!",error:"Non è stato possibile caricare il catalogo. Riprova tra poco.",quote:"Richiedi un preventivo",whatsapp:"Scrivici su WhatsApp",wa:"Ciao! Ho visto una creazione nel catalogo e vorrei maggiori informazioni su: "},pt:{back:"← Voltar ao site",kicker:"Nossas criações",title:"Ideias que viraram realidade.",intro:"Conheça alguns projetos realizados e fale conosco para criar o seu.",all:"Todos",loading:"Carregando as criações…",empty:"O catálogo será atualizado em breve. Conte sua ideia para a gente!",error:"Não foi possível carregar o catálogo. Tente novamente em instantes.",quote:"Pedir orçamento",whatsapp:"Chame no WhatsApp",wa:"Olá! Vi uma criação no catálogo e gostaria de mais informações sobre: "},en:{back:"← Back to website",kicker:"Our creations",title:"Ideas brought to life.",intro:"Explore some finished projects and contact us to create your own.",all:"All",loading:"Loading creations…",empty:"The catalogue will be updated soon. Tell us about your idea!",error:"The catalogue could not be loaded. Please try again shortly.",quote:"Request a quote",whatsapp:"Message us on WhatsApp",wa:"Hello! I saw a creation in the catalogue and would like more information about: "},es:{back:"← Volver al sitio",kicker:"Nuestras creaciones",title:"Ideas hechas realidad.",intro:"Descubre proyectos realizados y contáctanos para crear el tuyo.",all:"Todas",loading:"Cargando las creaciones…",empty:"El catálogo se actualizará pronto. ¡Cuéntanos tu idea!",error:"No se pudo cargar el catálogo. Inténtalo de nuevo pronto.",quote:"Pedir presupuesto",whatsapp:"Escríbenos por WhatsApp",wa:"¡Hola! Vi una creación en el catálogo y quisiera más información sobre: "},de:{back:"← Zurück zur Website",kicker:"Unsere Kreationen",title:"Ideen werden Wirklichkeit.",intro:"Entdecke fertige Projekte und kontaktiere uns für deine eigene Kreation.",all:"Alle",loading:"Kreationen werden geladen…",empty:"Der Katalog wird bald aktualisiert. Erzähl uns von deiner Idee!",error:"Der Katalog konnte nicht geladen werden. Bitte versuche es später erneut.",quote:"Angebot anfragen",whatsapp:"WhatsApp-Nachricht",wa:"Hallo! Ich habe eine Kreation im Katalog gesehen und möchte mehr Informationen zu: "}};
const collections={sensoriais:"Brinquedos sensoriais articulados",personagens:"Personagens",letreiros:"Letreiros para festa"};
const collectionCopy={
  it:{sensory:"Giochi sensoriali articolati",characters:"Personaggi",signs:"Scritte per feste",selectedIntro:"Esplora le creazioni di questa collezione.",collectionEmpty:"Non ci sono ancora creazioni in questa collezione."},
  pt:{sensory:"Brinquedos sensoriais articulados",characters:"Personagens",signs:"Letreiros para festa",selectedIntro:"Conheça as criações desta coleção.",collectionEmpty:"Ainda não há criações nesta coleção."},
  en:{sensory:"Articulated sensory toys",characters:"Characters",signs:"Party signs",selectedIntro:"Explore the creations in this collection.",collectionEmpty:"There are no creations in this collection yet."},
  es:{sensory:"Juguetes sensoriales articulados",characters:"Personajes",signs:"Letreros para fiestas",selectedIntro:"Descubre las creaciones de esta colección.",collectionEmpty:"Todavía no hay creaciones en esta colección."},
  de:{sensory:"Bewegliche Sinnesspielzeuge",characters:"Figuren",signs:"Schriftzüge für Feiern",selectedIntro:"Entdecke die Kreationen dieser Kollektion.",collectionEmpty:"In dieser Kollektion gibt es noch keine Kreationen."}
};
Object.keys(copy).forEach(code=>Object.assign(copy[code],collectionCopy[code]));
const cartCopy={
  it:{cart:"Carrello",addCart:"Aggiungi al carrello",added:"Aggiunto ✓",cartHint:"Rivedi gli articoli e invia la richiesta su WhatsApp.",cartEmpty:"Il carrello è vuoto.",cartNote:"Prezzi e disponibilità saranno confermati prima dell'ordine.",sendOrder:"Invia richiesta su WhatsApp",remove:"Rimuovi",subtotal:"Totale indicativo",quoteItems:"Articoli senza prezzo: preventivo da confermare",orderIntro:"Ciao! Vorrei chiedere questi articoli dal catalogo FS Studio Maker:",orderTotal:"Totale indicativo",orderQuote:"Prezzo da confermare",orderEnd:"Potete confermare disponibilità, prezzo finale e spedizione?",close:"Chiudi carrello"},
  pt:{cart:"Carrinho",addCart:"Adicionar ao carrinho",added:"Adicionado ✓",cartHint:"Confira os itens e envie o pedido pelo WhatsApp.",cartEmpty:"Seu carrinho está vazio.",cartNote:"Preços e disponibilidade serão confirmados antes do pedido.",sendOrder:"Enviar pedido pelo WhatsApp",remove:"Remover",subtotal:"Total estimado",quoteItems:"Itens sem preço: valor a confirmar",orderIntro:"Olá! Gostaria de pedir estes itens do catálogo FS Studio Maker:",orderTotal:"Total estimado",orderQuote:"Preço a confirmar",orderEnd:"Podem confirmar disponibilidade, valor final e entrega?",close:"Fechar carrinho"},
  en:{cart:"Cart",addCart:"Add to cart",added:"Added ✓",cartHint:"Review your items and send the request on WhatsApp.",cartEmpty:"Your cart is empty.",cartNote:"Prices and availability will be confirmed before ordering.",sendOrder:"Send request on WhatsApp",remove:"Remove",subtotal:"Estimated total",quoteItems:"Items without a price: quote to be confirmed",orderIntro:"Hello! I would like these items from the FS Studio Maker catalogue:",orderTotal:"Estimated total",orderQuote:"Price to be confirmed",orderEnd:"Could you confirm availability, final price and delivery?",close:"Close cart"},
  es:{cart:"Carrito",addCart:"Añadir al carrito",added:"Añadido ✓",cartHint:"Revisa los artículos y envía la solicitud por WhatsApp.",cartEmpty:"Tu carrito está vacío.",cartNote:"Los precios y la disponibilidad se confirmarán antes del pedido.",sendOrder:"Enviar solicitud por WhatsApp",remove:"Quitar",subtotal:"Total estimado",quoteItems:"Artículos sin precio: presupuesto por confirmar",orderIntro:"¡Hola! Quisiera estos artículos del catálogo FS Studio Maker:",orderTotal:"Total estimado",orderQuote:"Precio por confirmar",orderEnd:"¿Pueden confirmar disponibilidad, precio final y entrega?",close:"Cerrar carrito"},
  de:{cart:"Warenkorb",addCart:"In den Warenkorb",added:"Hinzugefügt ✓",cartHint:"Prüfe deine Artikel und sende die Anfrage per WhatsApp.",cartEmpty:"Dein Warenkorb ist leer.",cartNote:"Preise und Verfügbarkeit werden vor der Bestellung bestätigt.",sendOrder:"Anfrage per WhatsApp senden",remove:"Entfernen",subtotal:"Voraussichtlicher Gesamtpreis",quoteItems:"Artikel ohne Preis: Angebot folgt",orderIntro:"Hallo! Ich interessiere mich für diese Artikel aus dem FS Studio Maker Katalog:",orderTotal:"Voraussichtlicher Gesamtpreis",orderQuote:"Preis auf Anfrage",orderEnd:"Könnt ihr Verfügbarkeit, Endpreis und Versand bestätigen?",close:"Warenkorb schließen"}
};
Object.keys(copy).forEach(code=>Object.assign(copy[code],cartCopy[code]));
const requestedCollection=new URLSearchParams(location.search).get("colecao");
let collection=Object.hasOwn(collections,requestedCollection)?requestedCollection:"todos";
let creations=[],lang=localStorage.getItem("fs-language")||"it";const grid=document.querySelector("#catalog-grid"),select=document.querySelector("#language-select");
const cartKey="fs-studio-cart-v1";
let cart={};
try{const stored=JSON.parse(localStorage.getItem(cartKey)||"{}");if(stored&&typeof stored==="object"&&!Array.isArray(stored))cart=stored}catch{}
const cartPanel=document.querySelector("#cart-panel"),cartBackdrop=document.querySelector("#cart-backdrop"),cartTrigger=document.querySelector("#cart-trigger");
function cartQuantity(id){const n=Number(cart[id]);return Number.isSafeInteger(n)&&n>0?Math.min(n,99):0}
function cartEntries(){return Object.keys(cart).map(id=>({item:creations.find(x=>String(x.id)===id),qty:cartQuantity(id)})).filter(row=>row.item&&row.qty)}
function euro(value){return new Intl.NumberFormat(lang,{style:"currency",currency:"EUR"}).format(value)}
function saveCart(){localStorage.setItem(cartKey,JSON.stringify(cart));renderCart()}
function renderCart(){const t=copy[lang]||copy.it,rows=cartEntries(),count=rows.reduce((n,row)=>n+row.qty,0);document.querySelector("#cart-count").textContent=count;const holder=document.querySelector("#cart-items"),total=document.querySelector("#cart-total"),checkout=document.querySelector("#cart-checkout");holder.innerHTML=rows.length?rows.map(({item,qty})=>`<div class="cart-row"><div class="cart-row-info"><strong>${safe(localized(item,"title"))}</strong><small>${item.show_price&&item.price!=null?euro(item.price):safe(t.orderQuote)}</small></div><div class="cart-row-actions"><button type="button" data-cart-minus="${attr(String(item.id))}" aria-label="−">−</button><span>${qty}</span><button type="button" data-cart-plus="${attr(String(item.id))}" aria-label="+">+</button><button type="button" class="cart-remove" data-cart-remove="${attr(String(item.id))}">${safe(t.remove)}</button></div></div>`).join(""):`<p class="cart-empty">${safe(t.cartEmpty)}</p>`;const priced=rows.filter(({item})=>item.show_price&&item.price!=null),sum=priced.reduce((n,{item,qty})=>n+Number(item.price)*qty,0);total.textContent=priced.length?`${t.subtotal}: ${euro(sum)}${priced.length<rows.length?` · ${t.quoteItems}`:""}`:"";checkout.hidden=!rows.length;if(!rows.length){checkout.removeAttribute("href");return}const lines=[t.orderIntro,"",...rows.map(({item,qty},i)=>`${i+1}. ${qty}× ${localized(item,"title")} — ${item.show_price&&item.price!=null?euro(Number(item.price)*qty):t.orderQuote}`)];if(priced.length)lines.push("",`${t.orderTotal}: ${euro(sum)}${priced.length<rows.length?` (${t.quoteItems})`:""}`);lines.push("",t.orderEnd);checkout.href=`https://wa.me/${cfg.whatsapp}?text=${encodeURIComponent(lines.join("\n"))}`}
function toggleCart(open){cartPanel.hidden=!open;cartBackdrop.hidden=!open;cartTrigger.setAttribute("aria-expanded",String(open));document.body.classList.toggle("cart-open",open);if(open){renderCart();document.querySelector("#cart-close").focus()}else cartTrigger.focus()}
cartTrigger.addEventListener("click",()=>toggleCart(true));document.querySelector("#cart-close").addEventListener("click",()=>toggleCart(false));cartBackdrop.addEventListener("click",()=>toggleCart(false));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!cartPanel.hidden)toggleCart(false)});
document.querySelector("#cart-items").addEventListener("click",e=>{const button=e.target.closest("button");if(!button)return;const id=button.dataset.cartPlus??button.dataset.cartMinus??button.dataset.cartRemove;if(!id)return;if(button.hasAttribute("data-cart-remove"))delete cart[id];else if(button.hasAttribute("data-cart-plus"))cart[id]=Math.min(99,cartQuantity(id)+1);else if(cartQuantity(id)<=1)delete cart[id];else cart[id]=cartQuantity(id)-1;saveCart()});
grid.addEventListener("click",e=>{const button=e.target.closest("[data-add-cart]");if(!button)return;const id=button.dataset.addCart;if(!creations.some(item=>String(item.id)===id))return;cart[id]=Math.min(99,cartQuantity(id)+1);saveCart();const t=copy[lang]||copy.it;button.textContent=t.added;window.setTimeout(()=>{if(button.isConnected)button.textContent=(copy[lang]||copy.it).addCart},1100)});
function safe(value){const node=document.createElement("span");node.textContent=value||"";return node.innerHTML}
function attr(value){return safe(value).replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function applyLanguage(){const t=copy[lang]||copy.it;document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{if(t[el.dataset.i18n])el.textContent=t[el.dataset.i18n]});if(collection!=="todos"){const key={sensoriais:"sensory",personagens:"characters",letreiros:"signs"}[collection];document.querySelector('[data-i18n="title"]').textContent=t[key];document.querySelector('[data-i18n="intro"]').textContent=t.selectedIntro}document.querySelectorAll("[data-collection]").forEach(button=>button.classList.toggle("active",button.dataset.collection===collection));select.value=lang;localStorage.setItem("fs-language",lang);document.querySelector("#footer-wa").href=`https://wa.me/${cfg.whatsapp}?text=${encodeURIComponent(t.wa)}`;document.querySelector("#cart-close").setAttribute("aria-label",t.close);render();renderCart()}
function isVideo(path){return /\.(mp4|webm)$/i.test(path||"")}
function localized(item,field){return item.translations?.[lang]?.[field]?.trim()||item[field]||""}
function categoryCollection(value){
  const name=(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
  if(name.includes("personagen")||name.includes("colecionaveis"))return "personagens";
  if(name.includes("letreiro"))return "letreiros";
  if(name.includes("sensoria")||name.includes("articulad"))return "sensoriais";
  return null;
}
function render(){
  if(!creations.length)return;
  const t=copy[lang]||copy.it;
  const visible=collection==="todos"?creations:creations.filter(item=>categoryCollection(item.category)===collection);
  if(!visible.length){grid.innerHTML=`<div class="state"><p>${safe(t.collectionEmpty)}</p></div>`;return}
  grid.innerHTML=visible.map(item=>{
    const title=localized(item,"title"),description=localized(item,"description"),category=localized(item,"category");
    const media=(item.creation_images||[]).sort((a,b)=>Number(isVideo(a.storage_path))-Number(isVideo(b.storage_path))||a.sort_order-b.sort_order);
    const slides=media.length?media.map(entry=>{
      const url=attr(db.storage.from("creations").getPublicUrl(entry.storage_path).data.publicUrl);
      return `<div class="media-slide">${isVideo(entry.storage_path)?`<video src="${url}" controls playsinline preload="metadata" aria-label="${attr(title)}"></video>`:`<img src="${url}" alt="${attr(title)}" loading="lazy">`}</div>`;
    }).join(""):`<div class="media-slide"><img src="assets/colecionaveis.jpg" alt="${attr(title)}" loading="lazy"></div>`;
    const price=item.show_price&&item.price!=null?new Intl.NumberFormat(lang,{style:"currency",currency:"EUR"}).format(item.price):t.quote;
    const wa=`https://wa.me/${cfg.whatsapp}?text=${encodeURIComponent(t.wa+title)}`;
    return `<article class="creation-card"><div class="card-image"><div class="media-track" tabindex="0" aria-label="${attr(title)}">${slides}</div>${media.length>1?`<button type="button" class="media-arrow media-prev" aria-label="Anterior">‹</button><button type="button" class="media-arrow media-next" aria-label="Próximo">›</button><span class="image-count">1/${media.length}</span>`:""}</div><div class="card-content">${category?`<span class="category">${safe(category)}</span>`:""}<h2>${safe(title)}</h2><p>${safe(description)}</p><div class="card-bottom"><strong class="price">${safe(price)}</strong><a class="card-cta" href="${attr(wa)}" target="_blank" rel="noopener">WhatsApp ↗</a></div><button type="button" class="add-cart" data-add-cart="${attr(String(item.id))}">${safe(t.addCart)}</button></div></article>`;
  }).join("");
  grid.querySelectorAll(".card-image").forEach(card=>{
    const track=card.querySelector(".media-track"),count=card.querySelector(".image-count");
    if(!count)return;
    const update=()=>{const index=Math.round(track.scrollLeft/track.clientWidth);count.textContent=`${index+1}/${track.children.length}`;track.querySelectorAll("video").forEach((video,i)=>{if(i!==index)video.pause()})};
    card.querySelector(".media-prev").addEventListener("click",()=>track.scrollBy({left:-track.clientWidth,behavior:"smooth"}));
    card.querySelector(".media-next").addEventListener("click",()=>track.scrollBy({left:track.clientWidth,behavior:"smooth"}));
    track.addEventListener("scroll",update,{passive:true});
  });
}
async function load(){
  const {data,error}=await db.from("creations").select("id,title,description,category,translations,price,show_price,featured,sort_order,created_at,creation_images(storage_path,alt_text,sort_order)").eq("published",true).order("featured",{ascending:false}).order("sort_order").order("created_at",{ascending:false});
  if(error){grid.innerHTML=`<div class="state"><p>${(copy[lang]||copy.it).error}</p></div>`;return}
  creations=data||[];
  if(!creations.length){grid.innerHTML=`<div class="state"><p>${(copy[lang]||copy.it).empty}</p></div>`;return}
  render();renderCart();
}
document.querySelectorAll("[data-collection]").forEach(button=>button.addEventListener("click",()=>{collection=button.dataset.collection;const url=new URL(location.href);if(collection==="todos")url.searchParams.delete("colecao");else url.searchParams.set("colecao",collection);history.replaceState(null,"",url);applyLanguage()}));
select.addEventListener("change",e=>{lang=e.target.value;applyLanguage()});document.querySelector("#year").textContent=new Date().getFullYear();applyLanguage();load();
