const translations={
it:{navHome:"Home",navCreations:"Creazioni",navProcess:"Come funziona",navAbout:"Chi siamo",navContact:"Contatti",quote:"Richiedi un preventivo",shipping:"Spedizioni in tutta Europa",heroTitle:"Diamo forma alle tue idee, <em>in 3D.</em>",heroText:"Oggetti unici, accessori e creazioni personalizzate realizzati con cura, colore e tecnologia.",heroCta:"Crea il tuo progetto",discover:"Scopri le creazioni",custom:"Personalizzabile",languages:"Lingue disponibili",delivery:"Consegna europea",made:"Creato da FS Studio Maker",portfolioKicker:"Il nostro mondo",portfolioTitle:"Creazioni che non passano inosservate.",portfolioText:"Dall'idea all'oggetto finito: ogni pezzo nasce per raccontare qualcosa di tuo.",catCollectibles:"Collezionabili personalizzati",catCollectiblesText:"Personaggi e oggetti decorativi pieni di personalità.",catAccessories:"Accessori su misura",catAccessoriesText:"Soluzioni utili, colorate e create per te.",catKeychains:"Portachiavi e piccoli regali",catKeychainsText:"Dettagli personalizzati da portare sempre con te.",processKicker:"Semplice e personale",processTitle:"Dalla tua idea alla realtà.",processText:"Raccontaci cosa immagini. Ti accompagniamo in ogni fase fino alla consegna.",step1Title:"Condividi la tua idea",step1Text:"Inviaci una foto, un disegno o semplicemente raccontaci il progetto.",step2Title:"Definiamo i dettagli",step2Text:"Scegliamo insieme formato, colori e personalizzazioni.",step3Title:"Creiamo e spediamo",step3Text:"Realizziamo il tuo pezzo e lo spediamo in tutta Europa.",aboutKicker:"Creatività, tecnica e passione",aboutTitle:"Ogni progetto merita di diventare qualcosa di speciale.",aboutText:"FS Studio Maker trasforma idee in oggetti attraverso la stampa 3D. Realizziamo creazioni personalizzate con attenzione ai dettagli, dalla singola idea alle piccole collezioni.",ctaKicker:"Hai un'idea?",ctaTitle:"Creiamola insieme.",ctaText:"Scrivici su WhatsApp e raccontaci il progetto che hai in mente.",ctaButton:"Parla con noi",footerLocation:"Marega di Bevilacqua · Spedizioni in tutta Europa",wa:"Ciao! Ho visto il sito di FS Studio Maker e vorrei richiedere un preventivo."},
pt:{navHome:"Início",navCreations:"Criações",navProcess:"Como funciona",navAbout:"Sobre",navContact:"Contato",quote:"Pedir orçamento",shipping:"Envios para toda a Europa",heroTitle:"Damos forma às suas ideias, <em>em 3D.</em>",heroText:"Objetos únicos, acessórios e criações personalizadas feitos com cuidado, cor e tecnologia.",heroCta:"Crie seu projeto",discover:"Conheça as criações",custom:"Personalizável",languages:"Idiomas disponíveis",delivery:"Entrega na Europa",made:"Criado pela FS Studio Maker",portfolioKicker:"Nosso mundo",portfolioTitle:"Criações que não passam despercebidas.",portfolioText:"Da ideia ao objeto final: cada peça nasce para contar algo sobre você.",catCollectibles:"Colecionáveis personalizados",catCollectiblesText:"Personagens e objetos decorativos cheios de personalidade.",catAccessories:"Acessórios sob medida",catAccessoriesText:"Soluções úteis, coloridas e criadas para você.",catKeychains:"Chaveiros e pequenos presentes",catKeychainsText:"Detalhes personalizados para levar sempre com você.",processKicker:"Simples e pessoal",processTitle:"Da sua ideia para a realidade.",processText:"Conte o que você imagina. Acompanhamos cada etapa até a entrega.",step1Title:"Compartilhe sua ideia",step1Text:"Envie uma foto, um desenho ou apenas conte como imagina o projeto.",step2Title:"Definimos os detalhes",step2Text:"Escolhemos juntos o tamanho, as cores e a personalização.",step3Title:"Criamos e enviamos",step3Text:"Produzimos sua peça e enviamos para toda a Europa.",aboutKicker:"Criatividade, técnica e paixão",aboutTitle:"Todo projeto merece se tornar algo especial.",aboutText:"A FS Studio Maker transforma ideias em objetos através da impressão 3D. Criamos peças personalizadas com atenção aos detalhes, desde uma ideia única até pequenas coleções.",ctaKicker:"Tem uma ideia?",ctaTitle:"Vamos criar juntos.",ctaText:"Fale conosco pelo WhatsApp e conte o projeto que você imaginou.",ctaButton:"Fale conosco",footerLocation:"Marega di Bevilacqua · Envios para toda a Europa",wa:"Olá! Vi o site da FS Studio Maker e gostaria de pedir um orçamento."},
en:{navHome:"Home",navCreations:"Creations",navProcess:"How it works",navAbout:"About",navContact:"Contact",quote:"Request a quote",shipping:"Shipping throughout Europe",heroTitle:"We bring your ideas to life, <em>in 3D.</em>",heroText:"Unique objects, accessories and custom creations made with care, colour and technology.",heroCta:"Create your project",discover:"Explore our work",custom:"Custom made",languages:"Languages available",delivery:"European delivery",made:"Made by FS Studio Maker",portfolioKicker:"Our world",portfolioTitle:"Creations made to stand out.",portfolioText:"From the first idea to the finished object, every piece tells your story.",catCollectibles:"Custom collectibles",catCollectiblesText:"Characters and decorative objects full of personality.",catAccessories:"Made-to-measure accessories",catAccessoriesText:"Useful, colourful solutions created for you.",catKeychains:"Keyrings and small gifts",catKeychainsText:"Personalised details to carry with you every day.",processKicker:"Simple and personal",processTitle:"From your idea to reality.",processText:"Tell us what you imagine. We guide you through every step until delivery.",step1Title:"Share your idea",step1Text:"Send a photo, a sketch, or simply describe the project.",step2Title:"Define the details",step2Text:"Together we choose the size, colours and custom touches.",step3Title:"We create and ship",step3Text:"We make your piece and ship it throughout Europe.",aboutKicker:"Creativity, skill and passion",aboutTitle:"Every project deserves to become something special.",aboutText:"FS Studio Maker turns ideas into objects through 3D printing. We create custom pieces with close attention to detail, from one-off ideas to small collections.",ctaKicker:"Have an idea?",ctaTitle:"Let's create it together.",ctaText:"Message us on WhatsApp and tell us about the project you have in mind.",ctaButton:"Talk to us",footerLocation:"Marega di Bevilacqua · Shipping throughout Europe",wa:"Hello! I saw the FS Studio Maker website and would like to request a quote."},
es:{navHome:"Inicio",navCreations:"Creaciones",navProcess:"Cómo funciona",navAbout:"Nosotros",navContact:"Contacto",quote:"Pedir presupuesto",shipping:"Envíos a toda Europa",heroTitle:"Damos forma a tus ideas, <em>en 3D.</em>",heroText:"Objetos únicos, accesorios y creaciones personalizadas hechos con cuidado, color y tecnología.",heroCta:"Crea tu proyecto",discover:"Descubre las creaciones",custom:"Personalizable",languages:"Idiomas disponibles",delivery:"Entrega europea",made:"Creado por FS Studio Maker",portfolioKicker:"Nuestro mundo",portfolioTitle:"Creaciones que no pasan desapercibidas.",portfolioText:"De la idea al objeto terminado: cada pieza nace para contar algo de ti.",catCollectibles:"Coleccionables personalizados",catCollectiblesText:"Personajes y objetos decorativos llenos de personalidad.",catAccessories:"Accesorios a medida",catAccessoriesText:"Soluciones útiles, coloridas y creadas para ti.",catKeychains:"Llaveros y pequeños regalos",catKeychainsText:"Detalles personalizados para llevar siempre contigo.",processKicker:"Simple y personal",processTitle:"De tu idea a la realidad.",processText:"Cuéntanos qué imaginas. Te acompañamos en cada etapa hasta la entrega.",step1Title:"Comparte tu idea",step1Text:"Envíanos una foto, un dibujo o simplemente describe el proyecto.",step2Title:"Definimos los detalles",step2Text:"Elegimos juntos el tamaño, los colores y la personalización.",step3Title:"Creamos y enviamos",step3Text:"Fabricamos tu pieza y la enviamos a toda Europa.",aboutKicker:"Creatividad, técnica y pasión",aboutTitle:"Cada proyecto merece convertirse en algo especial.",aboutText:"FS Studio Maker transforma ideas en objetos mediante impresión 3D. Creamos piezas personalizadas cuidando cada detalle, desde una idea única hasta pequeñas colecciones.",ctaKicker:"¿Tienes una idea?",ctaTitle:"Vamos a crearla juntos.",ctaText:"Escríbenos por WhatsApp y cuéntanos el proyecto que tienes en mente.",ctaButton:"Habla con nosotros",footerLocation:"Marega di Bevilacqua · Envíos a toda Europa",wa:"¡Hola! Vi la web de FS Studio Maker y quisiera pedir un presupuesto."},
de:{navHome:"Start",navCreations:"Kreationen",navProcess:"So funktioniert's",navAbout:"Über uns",navContact:"Kontakt",quote:"Angebot anfragen",shipping:"Versand in ganz Europa",heroTitle:"Wir bringen deine Ideen in Form, <em>in 3D.</em>",heroText:"Einzigartige Objekte, Accessoires und individuelle Kreationen – mit Sorgfalt, Farbe und Technik gefertigt.",heroCta:"Projekt starten",discover:"Kreationen entdecken",custom:"Personalisierbar",languages:"Verfügbare Sprachen",delivery:"Europaweite Lieferung",made:"Von FS Studio Maker gefertigt",portfolioKicker:"Unsere Welt",portfolioTitle:"Kreationen, die auffallen.",portfolioText:"Von der Idee bis zum fertigen Objekt: Jedes Stück erzählt deine Geschichte.",catCollectibles:"Individuelle Sammlerstücke",catCollectiblesText:"Figuren und Dekorationen mit viel Persönlichkeit.",catAccessories:"Accessoires nach Maß",catAccessoriesText:"Nützliche, farbenfrohe Lösungen für dich gemacht.",catKeychains:"Schlüsselanhänger und kleine Geschenke",catKeychainsText:"Persönliche Details für jeden Tag.",processKicker:"Einfach und persönlich",processTitle:"Von deiner Idee zur Realität.",processText:"Erzähl uns von deiner Idee. Wir begleiten dich bis zur Lieferung.",step1Title:"Teile deine Idee",step1Text:"Sende ein Foto, eine Skizze oder beschreibe einfach dein Projekt.",step2Title:"Details festlegen",step2Text:"Gemeinsam wählen wir Größe, Farben und Personalisierung.",step3Title:"Wir fertigen und versenden",step3Text:"Wir erstellen dein Stück und versenden es in ganz Europa.",aboutKicker:"Kreativität, Technik und Leidenschaft",aboutTitle:"Jedes Projekt verdient es, etwas Besonderes zu werden.",aboutText:"FS Studio Maker verwandelt Ideen mit 3D-Druck in Objekte. Wir fertigen individuelle Stücke mit Liebe zum Detail – vom Einzelstück bis zur kleinen Kollektion.",ctaKicker:"Du hast eine Idee?",ctaTitle:"Lass sie uns gemeinsam umsetzen.",ctaText:"Schreib uns auf WhatsApp und erzähl uns von deinem Projekt.",ctaButton:"Kontakt aufnehmen",footerLocation:"Marega di Bevilacqua · Versand in ganz Europa",wa:"Hallo! Ich habe die Website von FS Studio Maker gesehen und möchte ein Angebot anfragen."}
};
Object.assign(translations.it,{swipeHint:"Scorri lateralmente per vedere altri lavori",moreCreations:"Altre creazioni",moreCreationsText:"Nuovi progetti e idee personalizzate."});
Object.assign(translations.pt,{swipeHint:"Arraste para o lado para ver outros trabalhos",moreCreations:"Mais criações",moreCreationsText:"Novos projetos e ideias personalizadas."});
Object.assign(translations.en,{swipeHint:"Swipe sideways to see more work",moreCreations:"More creations",moreCreationsText:"New projects and custom ideas."});
Object.assign(translations.es,{swipeHint:"Desliza hacia un lado para ver más trabajos",moreCreations:"Más creaciones",moreCreationsText:"Nuevos proyectos e ideas personalizadas."});
Object.assign(translations.de,{swipeHint:"Seitlich wischen, um weitere Arbeiten zu sehen",moreCreations:"Weitere Kreationen",moreCreationsText:"Neue Projekte und individuelle Ideen."});
Object.assign(translations.it,{ideaNote:"La tua idea<br>diventa reale",benefitUnique:"Pezzi unici",benefitUniqueText:"Creati su misura",benefitQuality:"Alta qualità",benefitQualityText:"Cura in ogni dettaglio",benefitEurope:"Spedizione europea",benefitEuropeText:"Direttamente a casa tua",benefitIdeas:"Idee che prendono forma",benefitIdeasText:"Dal progetto alla realtà",productionKicker:"Dietro le quinte",productionTitle:"Guarda come nascono le nostre creazioni.",productionText:"Scorri i video, aprili a schermo intero e scopri ogni dettaglio."});
Object.assign(translations.pt,{ideaNote:"Sua ideia<br>vira realidade",benefitUnique:"Peças únicas",benefitUniqueText:"Criadas sob medida",benefitQuality:"Alta qualidade",benefitQualityText:"Cuidado em cada detalhe",benefitEurope:"Envio para a Europa",benefitEuropeText:"Direto para sua casa",benefitIdeas:"Ideias que ganham forma",benefitIdeasText:"Do projeto à realidade",productionKicker:"Por trás da criação",productionTitle:"Veja como nascem as nossas criações.",productionText:"Arraste os vídeos, abra em tela cheia e descubra cada detalhe."});
Object.assign(translations.en,{ideaNote:"Your idea<br>made real",benefitUnique:"Unique pieces",benefitUniqueText:"Made just for you",benefitQuality:"High quality",benefitQualityText:"Care in every detail",benefitEurope:"European delivery",benefitEuropeText:"Straight to your home",benefitIdeas:"Ideas take shape",benefitIdeasText:"From concept to reality",productionKicker:"Behind the scenes",productionTitle:"See how our creations come to life.",productionText:"Swipe the videos, open them full screen and discover every detail."});
Object.assign(translations.it,{delivery:"Spedizione in Europa"});
Object.assign(translations.pt,{delivery:"Envio para a Europa"});
Object.assign(translations.en,{delivery:"Shipping across Europe"});
Object.assign(translations.es,{delivery:"Envío por Europa"});
Object.assign(translations.de,{delivery:"Versand in Europa"});
Object.assign(translations.it,{delivery:"Spedizione",checkDelivery:"Verifica la zona di consegna",deliveryWa:"Ciao! Vorrei verificare la disponibilità della consegna nella mia zona. È possibile?"});
Object.assign(translations.pt,{delivery:"Frete",checkDelivery:"Verificar região de entrega",deliveryWa:"Olá! Quero verificar a disponibilidade de entrega para a minha região. É possível?"});
Object.assign(translations.en,{delivery:"Shipping",checkDelivery:"Check delivery area",deliveryWa:"Hello! I would like to check whether delivery is available in my area. Is it possible?"});
Object.assign(translations.es,{delivery:"Envío",checkDelivery:"Consultar zona de entrega",deliveryWa:"¡Hola! Quisiera verificar si hay entrega disponible en mi zona. ¿Es posible?"});
Object.assign(translations.de,{delivery:"Versand",checkDelivery:"Liefergebiet prüfen",deliveryWa:"Hallo! Ich möchte prüfen, ob eine Lieferung in meine Region möglich ist. Ist das möglich?"});
Object.assign(translations.it,{footerWhatsapp:"Scrivici su WhatsApp"});
Object.assign(translations.pt,{footerWhatsapp:"Chame no WhatsApp"});
Object.assign(translations.en,{footerWhatsapp:"Message us on WhatsApp"});
Object.assign(translations.es,{footerWhatsapp:"Escríbenos por WhatsApp"});
Object.assign(translations.de,{footerWhatsapp:"Schreib uns auf WhatsApp"});
Object.assign(translations.es,{ideaNote:"Tu idea<br>hecha realidad",benefitUnique:"Piezas únicas",benefitUniqueText:"Creadas a medida",benefitQuality:"Alta calidad",benefitQualityText:"Cuidado en cada detalle",benefitEurope:"Envío por Europa",benefitEuropeText:"Directo a tu casa",benefitIdeas:"Ideas que toman forma",benefitIdeasText:"Del proyecto a la realidad",productionKicker:"Detrás de escena",productionTitle:"Mira cómo nacen nuestras creaciones.",productionText:"Desliza los vídeos, ábrelos a pantalla completa y descubre cada detalle."});
Object.assign(translations.de,{ideaNote:"Deine Idee<br>wird Wirklichkeit",benefitUnique:"Einzigartige Stücke",benefitUniqueText:"Für dich gefertigt",benefitQuality:"Hohe Qualität",benefitQualityText:"Sorgfalt in jedem Detail",benefitEurope:"Europaweiter Versand",benefitEuropeText:"Direkt zu dir nach Hause",benefitIdeas:"Ideen nehmen Form an",benefitIdeasText:"Vom Entwurf zur Realität",productionKicker:"Hinter den Kulissen",productionTitle:"Sieh, wie unsere Kreationen entstehen.",productionText:"Wische durch die Videos, öffne sie im Vollbild und entdecke jedes Detail."});
const select=document.querySelector('#language-select');
function setLanguage(lang){const t=translations[lang]||translations.it;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=t[el.dataset.i18n];if(value!==undefined)el.innerHTML=value});document.querySelectorAll('[data-wa]').forEach(a=>a.href=`https://wa.me/393287036017?text=${encodeURIComponent(t.wa)}`);document.querySelectorAll('[data-shipping-wa]').forEach(a=>a.href=`https://wa.me/393287036017?text=${encodeURIComponent(t.deliveryWa)}`);localStorage.setItem('fs-language',lang);select.value=lang}
select.addEventListener('change',e=>setLanguage(e.target.value));setLanguage(localStorage.getItem('fs-language')||'it');
const shippingTrigger=document.querySelector('.shipping-trigger'),shippingProof=document.querySelector('.shipping-proof');
shippingTrigger.addEventListener('click',event=>{event.stopPropagation();const open=shippingProof.classList.toggle('open');shippingTrigger.setAttribute('aria-expanded',open)});
document.addEventListener('click',event=>{if(!shippingProof.contains(event.target)){shippingProof.classList.remove('open');shippingTrigger.setAttribute('aria-expanded','false')}});
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
document.querySelectorAll('.video-control').forEach(button=>{const video=button.closest('article').querySelector('video');button.addEventListener('click',()=>{if(video.paused){video.play();button.textContent='❚❚'}else{video.pause();button.textContent='▶'}});video.addEventListener('ended',()=>button.textContent='▶')});

document.querySelectorAll('[data-carousel]').forEach(carousel=>{
  const viewport=carousel.querySelector('.carousel-viewport');
  const slides=[...carousel.querySelectorAll('.media-slide')];
  const dotsBox=carousel.querySelector('.carousel-dots');
  let current=0;
  slides.forEach((_,index)=>{const dot=document.createElement('button');dot.type='button';dot.setAttribute('aria-label',`Vai al contenuto ${index+1}`);dot.addEventListener('click',()=>goTo(index));dotsBox.appendChild(dot)});
  const dots=[...dotsBox.children];
  function update(){slides.forEach((slide,index)=>slide.classList.toggle('is-active',index===current));dots.forEach((dot,index)=>dot.classList.toggle('is-active',index===current))}
  function goTo(index){current=(index+slides.length)%slides.length;viewport.scrollTo({left:slides[current].offsetLeft,behavior:'smooth'});update()}
  carousel.querySelector('.carousel-prev').addEventListener('click',()=>goTo(current-1));
  carousel.querySelector('.carousel-next').addEventListener('click',()=>goTo(current+1));
  let timer;
  viewport.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{const nearest=slides.reduce((best,slide,index)=>Math.abs(slide.offsetLeft-viewport.scrollLeft)<Math.abs(slides[best].offsetLeft-viewport.scrollLeft)?index:best,0);current=nearest;update()},80)},{passive:true});
  update();
});

document.querySelectorAll('.fullscreen-control').forEach(button=>button.addEventListener('click',()=>{
  const media=button.closest('.media-slide').querySelector('video,img');
  if(media.requestFullscreen) media.requestFullscreen();
  else if(media.webkitEnterFullscreen&&media.tagName==='VIDEO') media.webkitEnterFullscreen();
}));

document.querySelectorAll('[data-scroll-gallery]').forEach(gallery=>{
  const progress=gallery.parentElement.querySelector('.gallery-progress span');
  const update=()=>{const max=gallery.scrollWidth-gallery.clientWidth;const ratio=max>0?gallery.scrollLeft/max:0;progress.style.transform=`scaleX(${Math.max(.18,ratio)})`};
  gallery.addEventListener('scroll',update,{passive:true});update();
});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.querySelector('#year').textContent=new Date().getFullYear();
